# Open dataframe

In [1]:
import numpy as np
import scipy as sp
import pandas as pd

import rpy2.rinterface
%load_ext rpy2.ipython

In [2]:
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
%%R -o df

df <- get(load("dpb.Rdata"))

In [4]:
df = df.rename(columns={'TARGET':'y'})

In [5]:
df = df.drop(columns=['AMT_REQ_CREDIT_BUREAU_TOTAL'])

In [6]:
np.array([len(df[col].unique()) for col in df.columns])

array([    2,     1,     3,     2,     2,     8,   411,    35,    44,
          39,     7,     8,     5,     5,     6,    79, 11104,  9279,
        5265,     8,     2,     2,     2,     2,     2,     5,     9,
           3,     3,    22,     2,     2,     2,     2,     2,     2,
           4, 17575,    24,     8,    24,     7,  2851,     1,     2,
           2,     2,     2,     2,     2,     2,     2,     2,     1,
           2,     2,     2,     2,     2,     2,     2,     1,     2])

In [7]:
df_boolean = df.iloc[:, np.where(np.array([len(df[col].unique()) for col in df.columns]) == 2)[0]].copy()

In [8]:
for col in df_boolean.columns:
    df_boolean[col] = df_boolean[col] - 1
df_boolean

,y,FLAG_OWN_CAR,FLAG_OWN_REALTY,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,...,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_21
3,0,1,1,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,1,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
18,0,0,1,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
19,0,0,1,1,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21,0,1,1,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
213150,0,0,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
213153,0,1,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
213159,1,0,0,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
213162,0,1,1,1,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
213168,0,0,1,1,0,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [9]:
categorcial_names = df.iloc[:, np.where(np.array([len(df[col].unique()) for col in df.columns]) > 2)[0]].iloc[:, [0,6,7,8,9,10,15,16,18,19,21,23,24,25,26]].columns

In [10]:
df_categorical = df[categorcial_names].copy()
for col in df_categorical.columns:
    df_categorical[col] = df_categorical[col].astype("category")
df_categorical

,CODE_GENDER,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,OWN_CAR_AGE,OCCUPATION_TYPE,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,ORGANIZATION_TYPE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE
3,2,7,8,5,4,2,6,3,2,2,1,0,0,0,0
10,2,7,8,5,4,2,8,3,2,2,1,2,0,2,0
18,1,7,8,5,2,2,8,3,2,2,1,4,0,4,0
19,1,4,8,5,5,2,8,3,1,1,1,8,0,8,0
21,2,7,8,5,2,2,7,3,2,2,3,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
213150,2,7,8,2,4,6,8,1,3,3,1,10,0,10,0
213153,1,7,5,2,4,2,2,1,2,2,1,1,0,1,0
213159,1,7,8,5,2,6,8,3,3,3,1,0,0,0,0
213162,2,7,8,2,2,2,2,1,1,1,2,0,0,0,0
213168,1,7,2,3,4,2,8,3,1,1,1,0,0,0,0

In [11]:
lista_colonne_restanti = []
for col in df.columns:
    if col in df_boolean.columns:
        continue
    if col in df_categorical.columns:
        continue
    if len(df[col].unique()) < 2:
        continue
    lista_colonne_restanti.append(col)

In [12]:
lista_colonne_restanti

['CNT_CHILDREN',
 'AMT_INCOME_TOTAL',
 'AMT_CREDIT',
 'AMT_ANNUITY',
 'AMT_GOODS_PRICE',
 'REGION_POPULATION_RELATIVE',
 'DAYS_BIRTH',
 'DAYS_REGISTRATION',
 'DAYS_ID_PUBLISH',
 'CNT_FAM_MEMBERS',
 'HOUR_APPR_PROCESS_START',
 'EXT_SOURCE_2',
 'DAYS_LAST_PHONE_CHANGE']

In [13]:
df_numerical = df[lista_colonne_restanti].copy()

In [14]:
for col in df_numerical.columns:
    df_numerical[col] = (df_numerical[col]-df_numerical[col].mean())/df_numerical[col].std()

In [15]:
df_testset_raw = pd.read_csv("testset.csv")

In [16]:
df_testset_raw = df_testset_raw.rename(columns={'TARGET':'y'})

In [17]:
df_test = df_testset_raw.loc[:,df_boolean.columns.union(df_numerical.columns)].copy()
df_test_cat = df_testset_raw.loc[:,categorcial_names].copy()
for col in df_test_cat.columns:
    df_test_cat[col] = df_test_cat[col].astype("category")
df_test = df_test.join(pd.get_dummies(df_test_cat, drop_first=False))

In [18]:
df_test

,AMT_ANNUITY,AMT_CREDIT,AMT_GOODS_PRICE,AMT_INCOME_TOTAL,CNT_CHILDREN,CNT_FAM_MEMBERS,DAYS_BIRTH,DAYS_ID_PUBLISH,DAYS_LAST_PHONE_CHANGE,DAYS_REGISTRATION,...,OBS_60_CNT_SOCIAL_CIRCLE_25,OBS_60_CNT_SOCIAL_CIRCLE_26,OBS_60_CNT_SOCIAL_CIRCLE_29,DEF_60_CNT_SOCIAL_CIRCLE_0,DEF_60_CNT_SOCIAL_CIRCLE_1,DEF_60_CNT_SOCIAL_CIRCLE_2,DEF_60_CNT_SOCIAL_CIRCLE_3,DEF_60_CNT_SOCIAL_CIRCLE_4,DEF_60_CNT_SOCIAL_CIRCLE_5,DEF_60_CNT_SOCIAL_CIRCLE_6
0,5337.0,45000.0,45000.0,90000.0,0,2,-8362,-993,-570,-3222,...,0,0,0,1,0,0,0,0,0,0
1,28233.0,961146.0,688500.0,157500.0,0,1,-20952,-4494,-447,-803,...,0,0,0,1,0,0,0,0,0,0
2,32868.0,781920.0,675000.0,121500.0,1,3,-16740,-295,0,-4942,...,0,0,0,1,0,0,0,0,0,0
3,23850.0,239850.0,225000.0,144000.0,0,2,-19963,-3498,-863,-10665,...,0,0,0,0,1,0,0,0,0,0
4,39001.5,534204.0,495000.0,123750.0,1,3,-16573,-133,-923,-8239,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91354,27558.0,254700.0,225000.0,157500.0,0,1,-9327,-1982,-273,-8456,...,0,0,0,1,0,0,0,0,0,0
91355,12001.5,269550.0,225000.0,72000.0,0,1,-20775,-4090,0,-4388,...,0,0,0,1,0,0,0,0,0,0
91356,29979.0,677664.0,585000.0,153000.0,0,1,-14966,-5150,-1909,-6737,...,0,0,0,1,0,0,0,0,0,0
91357,20205.0,370107.0,319500.0,171000.0,0,2,-11961,-931,-322,-2562,...,0,0,0,1,0,0,0,0,0,0
91358,49117.5,675000.0,675000.0,157500.0,0,2,-16856,-410,-787,-5128,...,0,0,0,1,0,0,0,0,0,0

# Analysis

In [18]:
df_boolean_uno = df_boolean[df_boolean['y'] == 1]
indici_uno_training = df_boolean_uno.sample(n = 800).index
df_boolean_uno = df_boolean_uno.drop(indici_uno_training)
indici_uno_calibration = df_boolean_uno.index

In [19]:
df_boolean_zero = df_boolean[df_boolean['y'] == 0]
indici_zero_training = df_boolean_zero.sample(n = 13774).index
df_boolean_zero = df_boolean_zero.drop(indici_zero_training)
indici_zero_calibration = df_boolean_zero.index

In [20]:
indici_training = indici_zero_training.union(indici_uno_training)
indici_calibration = indici_zero_calibration.union(indici_uno_calibration)

In [21]:
df_boolean.loc[indici_training,:]

,y,FLAG_OWN_CAR,FLAG_OWN_REALTY,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,...,FLAG_DOCUMENT_10,FLAG_DOCUMENT_11,FLAG_DOCUMENT_13,FLAG_DOCUMENT_14,FLAG_DOCUMENT_15,FLAG_DOCUMENT_16,FLAG_DOCUMENT_17,FLAG_DOCUMENT_18,FLAG_DOCUMENT_19,FLAG_DOCUMENT_21
10,0,0,1,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1000,0,1,0,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
100013,0,1,1,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
100014,0,0,1,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
100027,0,0,1,1,0,1,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99971,0,0,1,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99974,0,0,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99985,0,0,1,1,1,1,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99989,0,0,1,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
99993,1,0,1,1,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [22]:
df_categorical.loc[indici_training,:]

,CODE_GENDER,NAME_TYPE_SUITE,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,OWN_CAR_AGE,OCCUPATION_TYPE,REGION_RATING_CLIENT,REGION_RATING_CLIENT_W_CITY,ORGANIZATION_TYPE,OBS_30_CNT_SOCIAL_CIRCLE,DEF_30_CNT_SOCIAL_CIRCLE,OBS_60_CNT_SOCIAL_CIRCLE,DEF_60_CNT_SOCIAL_CIRCLE
10,2,7,8,5,4,2,8,3,2,2,1,2,0,2,0
1000,1,7,8,5,4,6,2,3,3,2,2,0,0,0,0
100013,1,7,2,2,4,2,2,1,2,2,1,0,0,0,0
100014,1,6,8,5,2,2,8,4,3,3,1,0,0,0,0
100027,1,7,2,2,4,2,8,1,2,2,2,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99971,1,7,8,2,2,2,8,1,2,2,1,2,0,2,0
99974,1,7,4,2,2,2,8,4,2,2,4,0,0,0,0
99985,2,7,2,2,4,2,8,1,2,2,1,0,0,0,0
99989,1,7,2,2,2,2,8,1,3,3,3,4,0,4,0
99993,1,7,8,5,2,5,8,3,2,2,2,0,0,0,0

In [23]:
df_numerical.loc[indici_training,:]

,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_REGISTRATION,DAYS_ID_PUBLISH,CNT_FAM_MEMBERS,HOUR_APPR_PROCESS_START,EXT_SOURCE_2,DAYS_LAST_PHONE_CHANGE
10,-0.648601,-0.091469,0.762354,0.753002,0.752818,-0.154190,-0.090036,2.871659,0.795316,-1.238455,-1.370667,1.214401,1.168236
1000,-0.648601,0.204427,-0.802601,-0.797658,-0.805318,-0.083503,-1.089249,-0.282777,-0.001993,-1.238455,-0.124944,0.778409,-0.120670
100013,-0.648601,2.402543,3.085818,3.055347,3.066158,0.609697,-1.227315,-0.205883,-0.483326,-1.238455,1.120780,0.710185,-0.371703
100014,-0.648601,-2.200268,-1.357776,-1.347734,-1.358074,-0.083503,0.543201,-0.868061,-1.362032,-0.189097,-0.747805,-2.237192,-1.089711
100027,-0.648601,-0.441439,-0.020124,-0.022340,-0.026251,0.048482,-0.167598,0.974738,0.872867,-1.238455,0.186487,-0.316945,0.234285
...,...,...,...,...,...,...,...,...,...,...,...,...,...
99971,-0.648601,-0.441439,-1.357776,-1.347734,-1.358074,-0.227017,-1.585785,0.270565,-1.737613,-0.189097,-0.747805,0.039990,-0.790091
99974,-0.648601,-0.441439,-0.575301,-0.572440,-0.579008,-0.778636,1.273107,-1.070943,-0.564724,-0.189097,-0.436374,0.692590,-0.460779
99985,-0.648601,1.479300,-0.188041,-0.188723,-0.193436,0.308519,-0.126656,-0.295495,0.190925,-1.238455,-0.436374,1.057005,1.322095
99989,-0.648601,0.091481,-0.802601,-0.797658,-0.805318,-0.268780,-1.193652,-0.097344,-0.293613,-0.189097,-0.747805,-1.073796,-0.217844
99993,-0.648601,0.460744,1.472000,1.456189,1.459372,0.649321,0.710609,-0.735566,-0.812761,-0.189097,0.809349,-0.704306,-0.440534

In [24]:
np.array([len(df[col].unique()) for col in df_categorical.columns])

array([ 3,  7,  8,  5,  5,  6,  8,  5,  3,  3,  4, 24,  8, 24,  7])

In [25]:
df_training = df_boolean.loc[indici_training,:].join(pd.get_dummies(df_categorical.loc[indici_training,:], drop_first=False))
df_training = df_training.join(df_numerical.loc[indici_training,:])
df_training

,y,FLAG_OWN_CAR,FLAG_OWN_REALTY,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,...,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_REGISTRATION,DAYS_ID_PUBLISH,CNT_FAM_MEMBERS,HOUR_APPR_PROCESS_START,EXT_SOURCE_2,DAYS_LAST_PHONE_CHANGE
10,0,0,1,1,0,1,0,0,0,0,...,0.753002,0.752818,-0.154190,-0.090036,2.871659,0.795316,-1.238455,-1.370667,1.214401,1.168236
1000,0,1,0,1,0,1,0,0,0,0,...,-0.797658,-0.805318,-0.083503,-1.089249,-0.282777,-0.001993,-1.238455,-0.124944,0.778409,-0.120670
100013,0,1,1,1,0,1,0,0,0,0,...,3.055347,3.066158,0.609697,-1.227315,-0.205883,-0.483326,-1.238455,1.120780,0.710185,-0.371703
100014,0,0,1,1,0,1,0,0,0,0,...,-1.347734,-1.358074,-0.083503,0.543201,-0.868061,-1.362032,-0.189097,-0.747805,-2.237192,-1.089711
100027,0,0,1,1,0,1,0,1,0,0,...,-0.022340,-0.026251,0.048482,-0.167598,0.974738,0.872867,-1.238455,0.186487,-0.316945,0.234285
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99971,0,0,1,1,0,1,0,0,0,0,...,-1.347734,-1.358074,-0.227017,-1.585785,0.270565,-1.737613,-0.189097,-0.747805,0.039990,-0.790091
99974,0,0,1,0,0,1,0,0,0,0,...,-0.572440,-0.579008,-0.778636,1.273107,-1.070943,-0.564724,-0.189097,-0.436374,0.692590,-0.460779
99985,0,0,1,1,1,1,1,0,0,0,...,-0.188723,-0.193436,0.308519,-0.126656,-0.295495,0.190925,-1.238455,-0.436374,1.057005,1.322095
99989,0,0,1,1,0,1,0,0,0,0,...,-0.797658,-0.805318,-0.268780,-1.193652,-0.097344,-0.293613,-0.189097,-0.747805,-1.073796,-0.217844
99993,1,0,1,1,0,1,0,0,0,0,...,1.456189,1.459372,0.649321,0.710609,-0.735566,-0.812761,-0.189097,0.809349,-0.704306,-0.440534

In [26]:
df_calibration = df_boolean.loc[indici_calibration,:].join(pd.get_dummies(df_categorical.loc[indici_calibration,:], drop_first=False))
df_calibration = df_calibration.join(df_numerical.loc[indici_calibration,:])
df_calibration

,y,FLAG_OWN_CAR,FLAG_OWN_REALTY,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,...,AMT_ANNUITY,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_REGISTRATION,DAYS_ID_PUBLISH,CNT_FAM_MEMBERS,HOUR_APPR_PROCESS_START,EXT_SOURCE_2,DAYS_LAST_PHONE_CHANGE
100044,0,1,1,1,1,1,1,0,1,1,...,5.357737,4.047671,0.734366,-0.336370,-0.206771,-1.102458,-0.189097,0.186487,0.156917,-1.087011
100218,0,1,1,1,0,1,0,1,0,0,...,-0.797658,-0.805318,0.223750,-1.410190,-0.607212,-0.915949,0.860261,-0.124944,0.259181,-0.336612
100227,0,1,1,1,0,1,1,1,0,0,...,-0.188723,-0.193436,-1.007333,-1.112450,1.508857,-0.075699,-1.238455,0.497918,0.624203,1.527240
100304,0,0,1,1,0,1,1,0,0,0,...,0.272429,0.269937,1.677248,0.936927,2.461162,-0.244262,-1.238455,1.743642,1.262047,0.246432
100338,0,0,1,1,0,1,0,0,0,0,...,-0.022340,-0.026251,-0.514872,-0.118695,0.931855,1.531095,-1.238455,-1.682098,0.934965,2.476036
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99704,0,0,0,1,0,1,0,0,0,0,...,-0.370973,-0.376567,0.957402,0.383755,0.080695,-1.708772,-0.189097,-0.747805,-0.050003,1.177683
99710,0,0,1,1,0,1,1,0,0,0,...,-0.797658,-0.805318,-0.268780,-1.610123,0.214077,-1.469066,-1.238455,-2.304960,-0.796993,-0.539058
99771,0,0,1,0,0,1,0,0,0,0,...,-0.797658,-0.805318,1.677248,1.593365,-1.070943,1.045276,-1.238455,-0.124944,1.065507,-0.895363
99873,0,0,0,1,0,1,1,0,0,0,...,-0.797658,-0.805318,-0.115740,0.672396,1.366603,-0.906977,-0.189097,-1.370667,-0.309231,-0.401395
99907,0,1,1,1,0,1,0,0,0,0,...,-0.188723,-0.193436,0.060563,1.261280,-0.249950,0.732505,-0.189097,-1.059236,-0.524619,-1.089711

In [34]:
df_test = df_test.loc[:,df_calibration.columns]

KeyError: "['CODE_GENDER_1', 'CODE_GENDER_2', 'CODE_GENDER_3', 'NAME_TYPE_SUITE_1', 'NAME_TYPE_SUITE_2', 'NAME_TYPE_SUITE_3', 'NAME_TYPE_SUITE_4', 'NAME_TYPE_SUITE_5', 'NAME_TYPE_SUITE_6', 'NAME_TYPE_SUITE_7', 'NAME_INCOME_TYPE_1', 'NAME_INCOME_TYPE_2', 'NAME_INCOME_TYPE_3', 'NAME_INCOME_TYPE_4', 'NAME_INCOME_TYPE_5', 'NAME_INCOME_TYPE_6', 'NAME_INCOME_TYPE_7', 'NAME_INCOME_TYPE_8', 'NAME_EDUCATION_TYPE_1', 'NAME_EDUCATION_TYPE_2', 'NAME_EDUCATION_TYPE_3', 'NAME_EDUCATION_TYPE_4', 'NAME_EDUCATION_TYPE_5', 'NAME_FAMILY_STATUS_1', 'NAME_FAMILY_STATUS_2', 'NAME_FAMILY_STATUS_3', 'NAME_FAMILY_STATUS_4', 'NAME_FAMILY_STATUS_5', 'NAME_HOUSING_TYPE_1', 'NAME_HOUSING_TYPE_2', 'NAME_HOUSING_TYPE_3', 'NAME_HOUSING_TYPE_4', 'NAME_HOUSING_TYPE_5', 'NAME_HOUSING_TYPE_6', 'OWN_CAR_AGE_1', 'OWN_CAR_AGE_2', 'OWN_CAR_AGE_3', 'OWN_CAR_AGE_4', 'OWN_CAR_AGE_5', 'OWN_CAR_AGE_6', 'OWN_CAR_AGE_7', 'OWN_CAR_AGE_8', 'OCCUPATION_TYPE_1', 'OCCUPATION_TYPE_2', 'OCCUPATION_TYPE_3', 'OCCUPATION_TYPE_4', 'OCCUPATION_TYPE_5', 'ORGANIZATION_TYPE_1', 'ORGANIZATION_TYPE_2', 'ORGANIZATION_TYPE_3', 'ORGANIZATION_TYPE_4', 'OBS_30_CNT_SOCIAL_CIRCLE_348', 'DEF_30_CNT_SOCIAL_CIRCLE_34', 'OBS_60_CNT_SOCIAL_CIRCLE_344', 'DEF_60_CNT_SOCIAL_CIRCLE_24', 'NCM'] not in index"

df_test = df_boolean.loc[indici_test,:].join(pd.get_dummies(df_categorical.loc[indici_test,:], drop_first=False))
df_test = df_test.join(df_numerical.loc[indici_test,:])
df_test

In [27]:
df_test_wrong = df_test.copy()

df_test_wrong['y'] = (1 - df_test['y']).copy()

In [28]:
from sklearn.neural_network import MLPClassifier

clf = MLPClassifier(solver='lbfgs', alpha=1e-5,
                    hidden_layer_sizes=[165,165,165,165], random_state=1)

In [29]:
clf.fit(df_training.iloc[:,1:], df_training.iloc[:,0])

MLPClassifier(alpha=1e-05, hidden_layer_sizes=[165, 165, 165, 165],
              random_state=1, solver='lbfgs')

In [30]:
sum(clf.predict(df_calibration.iloc[:,1:]))

202

In [31]:
N_training = df_training.shape[0]
N_calibration = df_calibration.shape[0]
N_test = df_test.shape[0]

In [32]:
probs = np.transpose(clf.predict_proba(df_calibration.iloc[:,1:]))
df_calibration['NCM'] = [probs[1-df_calibration.iloc[i,0],i] for i in range(N_calibration)]
df_calibration = df_calibration.sort_values('NCM')
df_calibration

,y,FLAG_OWN_CAR,FLAG_OWN_REALTY,FLAG_EMP_PHONE,FLAG_WORK_PHONE,FLAG_CONT_MOBILE,FLAG_PHONE,FLAG_EMAIL,REG_REGION_NOT_LIVE_REGION,REG_REGION_NOT_WORK_REGION,...,AMT_GOODS_PRICE,REGION_POPULATION_RELATIVE,DAYS_BIRTH,DAYS_REGISTRATION,DAYS_ID_PUBLISH,CNT_FAM_MEMBERS,HOUR_APPR_PROCESS_START,EXT_SOURCE_2,DAYS_LAST_PHONE_CHANGE,NCM
38621,0,1,1,1,1,1,0,0,0,0,...,-1.358074,1.677248,-0.467158,-1.225323,1.031175,0.860261,1.432211,1.196817,-0.815734,1.068155e-73
6161,0,1,1,1,0,1,1,0,0,1,...,2.188532,-0.708640,-0.661405,1.852219,-1.719667,0.860261,-0.747805,1.365774,-0.382500,5.672642e-73
126953,0,1,1,1,0,1,1,0,1,1,...,4.047671,1.677248,0.385802,1.299173,-1.690826,-0.189097,1.432211,1.240831,-0.687518,1.432719e-69
65173,0,1,1,1,0,1,0,0,0,0,...,0.752818,-0.708640,0.143789,0.111749,-0.417311,2.958977,0.497918,0.697944,1.079160,5.973417e-67
67251,0,0,0,1,1,1,1,0,0,0,...,-0.376567,3.491912,-0.090946,1.098656,0.974133,0.860261,2.366504,0.884795,1.030573,7.903784e-65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53301,1,1,0,1,0,1,0,0,0,0,...,-0.805318,-0.268780,-0.824718,-1.384139,0.626112,-0.189097,0.186487,-0.298686,0.778190,1.000000e+00
53088,1,0,1,0,0,1,0,0,0,0,...,-1.061887,-1.007333,1.347258,-0.181336,0.890813,-0.189097,0.809349,-1.131379,-0.416241,1.000000e+00
208192,1,0,0,1,0,1,0,0,0,0,...,-0.026251,-0.154190,-1.367428,-0.679966,-0.835193,-1.238455,0.809349,-0.235105,-0.696966,1.000000e+00
204785,1,0,1,1,1,1,1,0,0,0,...,-1.061887,0.048482,-0.070475,-0.629984,1.413807,-0.189097,0.809349,1.041823,1.110201,1.000000e+00
137113,1,0,1,1,0,1,0,0,0,0,...,-0.026251,-0.083503,-0.740559,-0.942589,0.907477,-0.189097,0.497918,-2.312226,1.658155,1.000000e+00

In [33]:
probs = np.transpose(clf.predict_proba(df_test.iloc[:,1:]))
df_test['NCM'] = [probs[1-df_test.iloc[i,0],i] for i in range(N_test)]
df_test['p_val'] = 1 - np.array( [ np.searchsorted(df_calibration['NCM'].to_numpy(), val)+1 for val in df_test['NCM'] ] )/N_calibration

/home/br1/PythonProjects/PythonStats/.venv/lib/python3.10/site-packages/sklearn/base.py:493: FutureWarning: The feature names should match those that were passed during fit. Starting version 1.2, an error will be raised.
Feature names unseen at fit time:
- CODE_GENDER_F
- CODE_GENDER_M
- DEF_60_CNT_SOCIAL_CIRCLE_6
- NAME_EDUCATION_TYPE_Academic degree
- NAME_EDUCATION_TYPE_Higher education
- ...
Feature names seen at fit time, yet now missing:
- AMT_ANNUITY
- CODE_GENDER_1
- CODE_GENDER_2
- CODE_GENDER_3
- DEF_30_CNT_SOCIAL_CIRCLE_34
- ...

  warnings.warn(message, FutureWarning)

ValueError: could not convert string to float: 'Y'

In [ ]:
df_test_wrong['NCM'] = [probs[1-df_test_wrong.iloc[i,0],i] for i in range(N_test)]
df_test_wrong['p_val'] = 1 - np.array( [ np.searchsorted(df_calibration['NCM'].to_numpy(), val)+1 for val in df_test_wrong['NCM'] ] )/N_calibration

In [ ]:
(df_test['p_val'] < 0.05).mean()

In [ ]:
(df_test_wrong['p_val'] < 0.05).mean()

In [ ]:
(df_test[df_test['y'] == 1]['p_val'] < 0.04).mean()

In [ ]:
(df_test_wrong[df_test['y'] == 1]['p_val'] < 0.04).mean()

In [ ]:
df_test_wrong[df_test['y'] == 1]['p_val'].mean()

In [ ]:
df_test[df_test['y'] == 1]['p_val'].mean()

In [ ]:
def true_positive(p):
    return (1 - (df_test[df_test['y'] == 1]['p_val'] < p).mean())
def false_positive(p):
    return (1 - (df_test_wrong[df_test['y'] == 0]['p_val'] < p).mean())

In [ ]:
pd.DataFrame([(true_positive(p),false_positive(p)) for p in np.linspace(0,0.1,1001)], columns=['true_positive','false_positive']).plot(kind='line', x='false_positive', y='true_positive')
plt.plot(np.linspace(0,1,101),np.linspace(0,1,101))

In [ ]:
df_training.shape[0]